#### ✅ 1. Create array from Python list or tuple
##### Example 1 — List → Array

In [21]:
import numpy as np
a = np.array([2,3,4,5,6])
print(a)
a.dtype

[2 3 4 5 6]


dtype('int64')

#### Example 2 — Tuple → Array

In [22]:
a = np.array((1,2,3,4,5))
print(a)
a.dtype

[1 2 3 4 5]


dtype('int64')

#### ✅ 2. Nested lists → multi-dimensional arrays
##### Example:

In [23]:
a = np.array([(1,2,3,4),(2,3,4,5)])
print(a)
a.dtype

[[1 2 3 4]
 [2 3 4 5]]


dtype('int64')

#### ✅ 3. Explicit dtype specification

In [25]:
a = np.array([[1,2,3],[2,3,4]], dtype=complex)
print(a)
a.dtype

[[1.+0.j 2.+0.j 3.+0.j]
 [2.+0.j 3.+0.j 4.+0.j]]


dtype('complex128')

#### ⭐ 4. Creating Arrays With Placeholder Values

##### These avoid growing arrays (slow).

#### ✔ np.zeros() — array of zeros

In [26]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ✔ np.ones() — array of ones

In [29]:
np.ones((2,3,5), dtype=np.int16)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

#### ⭐ 5. Creating Numeric Sequences
##### ✔ np.arange() — like Python range, but returns array

In [30]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

#### It supports floats — Python range does NOT:

In [31]:
np.arange(1,5,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

##### 📌 Floating point precision may cause unpredictable length.

#### ⭐ 6. When arange uses floats — better to use linspace

##### Because float steps accumulate error.

##### ✔ np.linspace(start, end, num_elements)

##### You give number of elements, not step size.

In [33]:
np.linspace(1, 6, 4)

array([1.        , 2.66666667, 4.33333333, 6.        ])

#### ⭐ 1. np.zeros_like(a)

##### Creates an array of zeros with same shape and dtype as array a.

In [35]:
import numpy as np
a = np.array([[2,3,4,5],[1,2,3,4]])
b = np.zeros_like(a)
print(b)

[[0 0 0 0]
 [0 0 0 0]]


#### ⭐ 2. np.ones_like(a)

##### Creates an array of ones with same shape as a.

###### Example:

In [36]:
a = np.array([[2,3,4],[5,6,7]])
b = np.ones_like(a)
print(b)

[[1 1 1]
 [1 1 1]]


#### ⭐ 3. np.empty_like(a)

##### Creates an uninitialized array (random garbage values) same shape as a.

###### Example:

In [37]:
e = np.empty_like(a)
print(e)

[[4607182418800017408 4611686018427387904 4613937818241073152]
 [4611686018427387904 4613937818241073152 4616189618054758400]]


#### ⭐ 4. np.random.random()

##### Returns random values between 0 and 1.

In [38]:
##### Example: 1 value
np.random.random()

0.9129761735837322

##### Example: 2×3 array of random values

In [39]:
r = np.random.random((2, 3))
print(r)

[[0.20290576 0.38240282 0.34445165]
 [0.38707586 0.04778113 0.53899668]]


#### ⭐ 2. np.fromfile() (Very Simple Explanation)
##### ✔ What it does

##### Reads raw binary data from a file and converts it into a NumPy array.

##### ✔ Think of it like:

##### “Load numbers directly from a file into an array.”

##### ⭐ Example — Save array to file, then load it
##### Step 1: Save array to file

In [40]:
import numpy as np

arr = np.array([10, 20, 30, 40])
arr.tofile("numbers.bin")

##### This creates a file called numbers.bin storing the array.

##### Step 2: Read array from file

In [42]:
new_arr = np.fromfile("numbers.bin", dtype=np.int64)
print(new_arr)

[10 20 30 40]


#### ⭐ Think of fromfunction() like this:
##### 👉 “NumPy will call your function once for every position in the array.”

###### Your function decides what value goes into each position.

###### That’s it.

##### ⭐ Step-by-step SUPER EASY explanation

###### Suppose you want a 3×3 array.

###### NumPy will ask your function:

###### “What should go in position (0,0)?”

###### “What should go in position (0,1)?”

###### “What should go in position (0,2)?”

###### “What should go in position (1,0)?”

###### “What should go in position (1,1)?”
###### … and so on.

###### Your function gets row number (i) and column number (j)
###### and returns the value.

###### ⭐ Very simple example

In [43]:
import numpy as np

arr = np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
print(arr)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


Let’s understand this with words:

##### 🔹 At (0,0) → i=0, j=0 → 0+0 = 0
##### 🔹 At (0,1) → i=0, j=1 → 0+1 = 1
##### 🔹 At (1,0) → i=1, j=0 → 1+0 = 1
##### 🔹 At (2,2) → i=2, j=2 → 2+2 = 4

So NumPy fills the array:

##### [[0 1 2]
#####  [1 2 3]
##### [2 3 4]]

⭐ Why is this useful?

Because you can create big arrays without loops.

Example:

multiplication tables

distance grids

patterns

heatmaps

⭐ Another SUPER SIMPLE example

Create an array where value = row number:
